---
title: Nacho Verdón
timezone: Europe/Madrid
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nverblaz@gmail.com
description: My portfolio
keywords: Developer, Java, Haxe, Javascript, Python, HTML, Games
author: Nacho Verdón
baseurl: 
url: http://justht.ml/
title_image: http://i.imgur.com/23HNUKl.png
post_limit: 5
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
exclude:
- vendor
show_downloads: true
